### ISSUE TITLE
Job Error preservation

### ISSUE THREAD

**Issue by samuelgoldenbaum** [bee-queue/bee-queue#146] opened 2018-09-12 22:32 UTC
We seem to lose Error object properties on the job 'failed' event. Given the following scenario:

```
queue.process(function (job, done) {
    let error = new Error('oh no!');

    error.code = '100';
    error.name = 'APIError';
    error.foo = 'foo';

    throw error; // or done(error);
```
We would lose all the additional properties added to custom Errors when handling the following job event:
```
job.on('failed', (err) => {
    console.error(err); // only err.message and err.stack
});
```
I am not sure what the best way to handle this is, but I have added a default errorFormatter on the Queue object:
```
this.errorFormatter = function (err) {
            return err.message || err;
        };
```
which can be overridden:
```
const queue = new Queue('example');
queue.errorFormatter = function (err) {
    if (err.name === 'APIError') { // or whatever else you want to factor
        return err;
    }

    return err.message || err;
};
```
and then 
```
       if (message.event === 'failed' || message.event === 'retrying') {
            message.data = this.errorFormatter(message.data);
        }
```
and 
```
 _finishJob(err, data, job) {
       ...
        const jobEvent = {
            id: job.id,
            event: status,
            data: err ? this.errorFormatter(err) : data
        };
```

Its critical that we can preserver the Error properties. If there is a better solve, please let me know.

**Comment by skeggse** [comment] 2020-04-16 20:18
We can add support for [a `toJSON` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description) on error objects. Would that work for you? That'd provide a lot of control over how error objects get serialized. Alternately, we could add support for an Error formatted/dehydrator in the Queue settings. What do you think?

**Comment by skeggse** [comment] 2020-04-16 21:19
Duplicate of #40.

**Closed by skeggse** 2020-04-16 21:19 UTC
Labels: duplicate, enhancement
