### ISSUE TITLE
I have a question about README.md about save @1.2.2

### ISSUE THREAD

**Issue by FantasyNeurotic** [bee-queue/bee-queue#149] opened 2018-10-12 02:30 UTC
```js
const job = queue.createJob({x: 2, y: 3}).save()
job.on('succeeded', (result) => {
  console.log(`Received result for job ${job.id}: ${result}`)
})
```
I run the code but it throw the error.
`TypeError: job.on is not a function`
And we must use the way about that:
```js
const job = queue.createJob({x: 2, y: 3})
job.save()
job.on('succeeded', (result) => {
  console.log(`Received result for job ${job.id}: ${result}`)
})
```
The env:
```
* redis : 4.0.11
* node : v8.9.11
* node-redis : 2.8.0
```

**Comment by skeggse** [comment] 2020-04-16 20:13
The `save` function returns a `Promise<Job>` - you'll need to resolve the promise before you can interact with it.
```js
const job = await queue.createJob({x: 2, y: 3}).save()
job.on('succeeded', (result) => {
  console.log(`Received result for job ${job.id}: ${result}`)
})
```
Duplicate of #99. Fixed in 337c1213 / `v1.2.3`.

**Closed by skeggse** 2020-04-16 20:13 UTC
