### ISSUE TITLE
Ability to store simple result in job

### ISSUE THREAD

**Issue by ifeins** [bee-queue/bee-queue#115] opened 2018-04-29 13:15 UTC
Hi,

Is it possible to store a simple result (String, integer, etc.) in a job?
I want to be able to list to the user the waiting/currently running/completed jobs and for the completed jobs I want to display the result (in my case it's a file path on the server).

I know that I can use a database or manage some text file on the server but both options seem like an overkill, especially given that bee-queue already gives access to most of the data I need (the job's status, params, and timestamp).

Is there a way to do so?

**Comment by skeggse** [comment] 2020-04-16 20:47
Not currently, no. That'd be a fine addition to the existing functionality that lets us report the result of a job over pubsub, though!

**Comment by skeggse** [comment] 2020-04-16 21:08
Still happy to accept pull requests for this, but I'm marking this as a duplicate of #84.

**Closed by skeggse** 2020-04-16 21:08 UTC
Labels: enhancement
