### ISSUE TITLE
'success' event not fired

### ISSUE THREAD

**Issue by henchmun** [bee-queue/bee-queue#78] opened 2017-09-12 13:38 UTC
Hey there,

Thanks for the great library, although unfortunately I have been having a few issues,

I've been using bull and recently switched to bee queue to make use of the job success event callbacks that mean I can use async.js parallel to set of loads of tasks to be done by workers and wait for them all to complete,

My problem comes when the queue says that it has "completed" everything

```js
{ waiting: 0,
  active: 0,
  succeeded: 1250,
  failed: 0,
  delayed: 0,
  newestJob: 1250 }
```

But by my own logging:
```
Checked stalled jobs 0
Total: 1250 jobs
Outstanding: 10 jobs
```

10 Jobs didn't fire a callback, which then hangs my program which is waiting for the success callback of each job before it moves on to the next step

This is probably a scalability issue of where jobs are coming back to the dispatch too quickly to handle, as when jobs have a setTimeout in them of 100ms the queue doesn't hang. But in that case, I would expect for succeeded to be incorrect when calling checkHealth (although I know this is asking Redis instead of the library what it has seen). 

As all jobs have "succeeded" is there a way for me to then recall the data returned by these outstanding jobs? Or is there a way for me to forcefully retry them again?

For now I'm going to attempt to set a manual timeout to remove and save the job again.

Thanks for the hard work though, cheers for any help anyone may have for fixing this,

**Comment by Hunchmun** [comment] 2017-09-12 13:45
Just following up that my nasty hack does work:

```js
        let timeout = setTimeout(() => {
            console.log("Retrying:", job.id);
            job.remove((err, job) => {
                if (err) {
                    console.error(err);
                    throw err;
                } else {
                    job.save((err, job) => {
                        if (err) {
                            console.error(err);
                            throw err;
                        }
                    });
                }
            });

        }, this.settings.retryTime * 1000);
```

But anyway to ensure the consistency of the queue would be appreciated

**Comment by Hunchmun** [comment] 2017-09-12 14:23
Apologies for the spam, but I come back to you with some really meaningful data.

Bee-Queue or one of it's dependencies (maybe redis) doesn't handle arrays very well. One of my tasks returns an array, which would then cause all jobs within that lot to back up depending on how many were within the queue. 

Changing the array to an object meant that less jobs were being reported as successfully done without firing the callback. However, under extreme conditions, jobs would still need to be retried and it only managed to perform well with batches of 2500 jobs when the larger return values/objects were omitted.

**Comment by LewisJEllis** [comment] 2017-09-12 20:22
Interesting observation/hangup you've run into, and thanks for all the details @Hunchmun. There are a couple of possible "event loop blocked/socket got busy/job never got far enough before result came back" scenarios I'm imagining here and I'd like to investigate more - do you have a minimum viable repro snippet I can run for that last case you describe? I can probably imagine what it looks like, but I'd rather not go at it blind.

**Comment by pbadenski** [comment] 2017-10-18 12:41
Maybe related.. let me know if I'm mistaken. I'm also seeing some jobs not being properly processed (what looks like race condition). I added bunch of debugging statements and it seems that succeeded event is being ignored because the jobs Map (property of queue) does not have the job in it.

I've looked at [the code](https://github.com/bee-queue/bee-queue/blob/master/lib/job.js#L58-L80) and have been wondering why would jobs first be registered with redis (that's what `evalScript("addJob")` is doing I gather) and only then put on the internal `queue.jobs` structure... The other way around seems to have been safer.

**Comment by LewisJEllis** [comment] 2017-10-19 01:16
Oh, interesting - so if I'm understanding this correctly, it's possible that the following sequencing happens:
- producer runs `evalScript('addJob')` and redis creates id + job
- during latency for results of evalScript('addJob') to make it back to producer:
  - consumer takes job and completes it
  - succeeded event goes across pubsub
  - producer receives succeeded event
- succeeded event fires without corresponding job in jobs table to forward it to

I think we would then observe a queue-level event but not a job-level event. It seems unintuitive to me that such sequencing would ever be able to occur - I would think Redis's single-threadedness would not allow for such sequencing, but I can't be certain of that off the top of my head. It could also be some situation with callback/event loop queueing on the producer.

Let me know if this is what you believe is happening, and if you can confirm my hypothesized observation in your experiment. I can try to actually reproduce it, but it might be easier to just make a fix than to try to repro myself.

I would like to avoid turning it into two redis roundtrips though - I think that would likely cause a measurable (though probably fairly insignificant) decrease in job throughput. We can instead change the logic for dispatching job-level events to still work even if the job is registered later with some crafty promise tricks.

**Comment by pbadenski** [comment] 2017-10-19 09:32
Correct, this is what I believe is happening. I will make attempt to reproduce it to make sure with full confidence that this is a problem.

**Comment by pbadenski** [comment] 2017-10-20 15:23
I can definitely reproduce this. Unfortunately only at work on our system (close sourced). I have already made some attempts to isolate, but looks like this might take me a while.

Random thought I had, why not replace redis generated ids with client generated UUID? Then it would be easy to first assign id, then enqueue the job in redis.

**Comment by duytai** [comment] 2018-08-07 03:10
Encounter the same issue the "success" event is not fired, my program hangs forever

**Comment by hughsw** [comment] 2020-03-27 10:17
A PR with one approach to solving the problem is here #193

**Comment by skeggse** [comment] 2020-04-16 21:12
Closing in favor of the newer, more active #189.

**Closed by skeggse** 2020-04-16 21:12 UTC
Labels: bug
