### ISSUE TITLE
Any plans to support newer version of Node-Redis?

### ISSUE THREAD

**Issue by pSnehanshu** [bee-queue/bee-queue#690] opened 2023-09-09 08:47 UTC
The latest version of `node-redis` is 4.6.8, however BeeQueue is stuck in version 3.1.2. This version of `node-redis` doesn't even ships its own types. Any plan to upgrade to the latest version? Or at least include it as a peer dependency so that we can use our own version of `node-redis`?

**Comment by Manfredik** [comment] 2023-10-29 08:44
I will join the question, I like the tool and use it in production, I really want to see its development

**Comment by compwright** [comment] 2023-10-30 01:57
I'd love for us to get there. We need all the help we can get from any interested volunteers to make it happen. I seem to be the only active maintainer and haven't had the time to make it happen on my own. Interested in submitting any PRs?

**Comment by compwright** [comment] 2023-11-06 16:08
Duplicate of #481

**Closed by compwright** 2023-11-06 16:08 UTC
Labels: duplicate
