### ISSUE TITLE
bee-queue error with redis 4

### ISSUE THREAD

**Issue by cesco69** [bee-queue/bee-queue#459] opened 2022-01-12 08:06 UTC
Looks like Redis package has been officially updated to v4 recently, which introduced some [breaking changes](https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md), including several interface changes.

With redis 4, bee-queue raise this error:

```shell
node_modules/bee-queue/index.d.ts:5:21 - error TS2305: Module '"redis"' has no exported member 'RedisClient'.

5 import {ClientOpts, RedisClient} from 'redis';
```

**\node_modules\bee-queue\index.d.ts**

```ts

/// <reference types="node" />
/// <reference types="redis" />

import {EventEmitter} from 'events';
import {ClientOpts, RedisClient} from 'redis';
```

**package.json**

```
{
  "devDependencies": {
    "@types/body-parser": "^1.19.2",
    "@types/bull-arena": "^3.0.5",
    "@types/busboy": "^1.3.0",
    "@types/compression": "^1.7.2",
    "@types/cookie-parser": "^1.4.2",
    "@types/cors": "^2.8.12",
    "@types/express": "^4.17.13",
    "@types/express-session": "^1.17.4",
    "@types/jest": "^27.4.0",
    "@types/jsdom": "^16.2.14",
    "@types/jsonwebtoken": "^8.5.6",
    "@types/mongodb": "^4.0.7",
    "@types/mustache": "^4.1.2",
    "@types/node": "^17.0.8",
    "@types/nodemailer": "^6.4.4",
    "@types/request": "^2.48.8",
    "@types/sax": "^1.2.4",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "^5.9.1",
    "@typescript-eslint/parser": "^5.9.1",
    "eslint": "^8.6.0",
    "gulp": "^4.0.2",
    "jest": "^27.4.7",
    "nodemon": "^2.0.15",
    "sonar-scanner": "^3.1.0",
    "sonarqube-scanner": "^2.8.1",
    "supertest": "^6.2.0",
    "ts-jest": "^27.1.2",
    "tsutils": "^3.21.0",
    "typescript": "^4.5.4"
  },
  "dependencies": {
    "acca-srv-prodotti-client": "^3.3.10",
    "agentkeepalive": "^4.2.0",
    "aws-sdk": "^2.1054.0",
    "axios": "^0.24.0",
    "bee": "^0.1.1",
    "bee-queue": "^1.4.0",
    "body-parser": "^1.19.1",
    "bottleneck": "^2.19.5",
    "bull-arena": "^3.29.3",
    "busboy": "^1.3.0",
    "compression": "^1.7.3",
    "connect-redis": "^6.0.0",
    "cookie-parser": "^1.4.6",
    "copyfiles": "^2.4.1",
    "cors": "^2.8.4",
    "del": "^6.0.0",
    "express": "^4.17.2",
    "express-session": "^1.17.2",
    "express-socket.io-session": "^1.3.5",
    "fast-xml-parser": "^4.0.1",
    "gunzip-file": "^0.1.1",
    "html-entities": "^2.3.2",
    "iconv-lite": "^0.6.3",
    "jsdom": "^19.0.0",
    "jsonwebtoken": "^8.5.1",
    "mock-express-response": "^0.3.0",
    "mongodb": "^4.3.0",
    "mustache": "^4.2.0",
    "nodemailer": "^6.7.2",
    "proxy-agent": "^5.0.0",
    "qs": "^6.10.3",
    "queue": "^6.0.2",
    "redis": "^4.0.1",
    "response-time": "^2.3.2",
    "sax": "^1.2.4",
    "socket.io": "^4.4.1",
    "socket.io-client": "^4.4.1",
    "socket.io-redis": "^6.1.1",
    "tslib": "^2.3.1",
    "uuid": "^8.3.2"
  }
}
```

dirty working around

**typings.d.ts**

```ts
declare module "redis" {
    interface ClientOpts {
    }
    interface RedisClient {
    }
    function createClient(...args: any[]): any;
}
```

**Comment by bradvogel** [comment] 2022-02-17 14:04
We hadn't planned on it, but we'd be happy to take a PR

**Comment by evcohen** [comment] 2022-03-08 01:15
@cesco69 do you plan on taking this on?

**Comment by compwright** [comment] 2022-11-22 18:57
Duplicate of #481

**Closed by compwright** 2022-11-22 18:57 UTC
